# Generated by Django 4.2.7 on 2023-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationotc',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
