# Generated by Django 4.2.7 on 2023-11-24 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_registrationotc_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
